# plot 1

# What is mean total number of steps taken per day?

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.width = 10, fig.height = 5,
                      fig.keep = 'all' ,fig.path = 'figures\ ', dev = 'png')

activity<-read_csv("C:\\Users\\HP\\Documents\\R\\activity.csv")

print(activity)

day<-weekdays(activity$date)

print(day)

activity$date <- as.POSIXct(activity$date, "%Y%m%d")

activitywithdays<-cbind(activity, day)
activitywithdays

# Calculate the total number of steps taken per day

totalactivitydays<-aggregate(steps~date,activitywithdays, sum, na.rm=TRUE)
totalactivitydays

totalactivitydays<-as_tibble(totalactivitydays)

# Make a histogram of the total number of steps taken each day

b<-ggplot(totalactivitydays, aes(steps)) + geom_histogram(breaks=seq(0,25000, by=2500), fill='RED', colour='WHITE')
b + labs(x="Total Steps Taken Per Days", y="Frequency", title="Total Steps Taken Per Day",
         subtitle='Histogram')


# Calculate and report the mean and median of the total number of steps taken per day

mean(totalactivitydays$steps)
median(totalactivitydays$steps)


# plot 2

# What is the average daily activity pattern?

activitywithdays

averagepattern<-aggregate(steps~interval, activitywithdays, mean)

print(averagepattern)

averagepattern<-as_tibble(averagepattern)
print(averagepattern)

# Make a time series plot (i.e. \color{red}{\verb|type = "l"|}type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

f<-ggplot(averagepattern, aes(interval, steps)) + geom_line(colour='BLUE')
print(f)

f + labs(x='Interval', y='Avg Number Of Steps', title='Interval By Avg No Of Steps',
         subtitle='Interval By Avg No Of Steps - LINE CHART')


# Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

print(averagepattern)

subset(averagepattern, averagepattern$steps==max(averagepattern$steps))

averagepattern$interval[averagepattern$steps==max(averagepattern$steps)]



# plot 3

# Imputing missing values

# Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with \color{red}{\verb|NA|}NAs)

activity
sum(is.na(activity$steps))

# Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

imputedSteps <- averagepattern$steps[match(activity$interval, averagepattern$interval)]

activityImputed <- transform(activity, 
                             steps = ifelse(is.na(activity$steps), yes = imputedSteps, no = activity$steps))

print(activityImputed)

activityImputeddata<-aggregate(steps~date, activityImputed, sum)

activityImputeddata

activityImputeddata<-as_tibble(activityImputeddata)

print(activityImputeddata)

# Make a histogram of the total number of steps taken each day

t<-ggplot(activityImputeddata, aes(steps)) + geom_histogram(breaks=seq(0,25000, by=2500), fill='BLUE', colour='WHITE')

t + labs(x="Total Steps Taken Per Day", y='Frequency', title='Total Step Taken Per Day by Frequency')


# Calculate and report the mean and median total number of steps taken per day

mean(activityImputeddata$steps)

median(activityImputeddata$steps)


# plot 4

# Are there differences in activity patterns between weekdays and weekends?

# Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.

activity$date <- as.Date(strptime(activity$date, format="%Y-%m-%d"))


activity$dayType <- sapply(activity$date, function(x) {
  if(weekdays(x) == "Saturday" | weekdays(x) == "Sunday")
  {y <- "Weekend"}
  else {y <- "Weekday"}
  y
})


# Make a panel plot containing a time series plot (i.e. \color{red}{\verb|type = "l"|}type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.

activitydata<-aggregate(steps~interval+dayType,activity, mean)

print(activitydata)

w<-ggplot(activitydata, aes(interval, steps))+ geom_line(colour='BLUE') + facet_wrap(~dayType)

w + labs(x="Interval", y='Average  No Of Steps', title='Average Daily Steps')









